---
abstract: 'jQuery QapTcha Plugin for Mojolicious'
author:
  - 'Holger Rupprecht <holger.rupprecht@gmx.de>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4204, CPAN::Meta::Converter version 2.130880'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-Qaptcha
no_index:
  file:
    - README.pod
provides:
  Mojolicious::Plugin::Qaptcha:
    file: lib/Mojolicious/Plugin/Qaptcha.pm
    version: 0.08
requires:
  File::ShareDir: 1.00
  Mojolicious: 4
resources:
  bugtracker: http://github.com/hrupprecht/Mojolicious-Plugin-Qaptcha/issues
  license: http://www.perlfoundation.org/artistic_license_2_0
  repository: http://github.com/hrupprecht/Mojolicious-Plugin-Qaptcha
version: 0.08
